### ISSUE TITLE
Error while bundling: no such file or directory, open 'xxx\node_modules\angular2-jwt.js'

### ISSUE THREAD

**Issue by Marcelh29** [mgechev/angular-seed#1499]
I added angular2-jwt like described in: https://github.com/mgechev/angular-seed/wiki/Add-external-dependency:

Project.Config.ts
this.SYSTEM_CONFIG_DEV.paths['angular2-jwt'] = `${this.APP_BASE}node_modules/angular2-jwt/angular2-jwt`;
 this.SYSTEM_BUILDER_CONFIG.packages['angular2-jwt'] = { main: 'angular2-jwt.js', defaultExtension: 'js' };

While bundling in the prod build it gives the following error:  

[14:00:21] Starting 'build.bundles.app'...
[14:00:22] 'build.bundles.app' errored after 1.06 s
[14:00:22] Error on fetch for angular2-jwt.js at file:///xxx/node_modules/angular2-jwt.js
	Loading dist\tmp\app\app.module.js
	Loading dist\tmp\app\main.js
	Error: ENOENT: no such file or directory, open 'xxx\node_modules\angular2-jwt.js'
    at Error (native)

Same issue occurs for moment, primeng and ng2-transate for which I added SYSTEM_CONFIG_DEV.paths in the project.config.ts

What should I do to fix this?

**Comment by hhubik** [comment]
I wonder if this is related.

Loaded the latest Seed last night and `require` stopped working for some of my external libraries.

For example, `var saveAs = require('file-saver');` used to work before the update.  Now my app fails to load with this message:

`Error loading http://localhost:5555/node_modules/file-saver.js as "file-saver" from http://localhost:5555/app/shared/services/data.service.js ` 

The file that used to get and should be getting loaded is `node_modules/file-saver/FileSaver.js`.

Any suggestions?

**Comment by iherbivore** [comment]
@Marcelh29 I am using `angular2-jwt` and I do not have listed in any of the seed config files. I only import it in my app.module like `import { AuthHttp, AuthConfig } from 'angular2-jwt/angular2-jwt';`

I did recently have to pin it to version `0.1.23`. Version `0.1.24` uses `js-base64` ( or something like that) and I could not get the seed configured to work with that no matter what I tried. If you manage that part please let me know.

**Comment by iherbivore** [comment]
@Marcelh29 These are the relevant entries from my project.config:

```
  this.mergeObject( this.SYSTEM_CONFIG.paths, {
      [this.BOOTSTRAP_MODULE]: `${this.APP_INDEX}${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      'app/*': `${this.APP_INDEX}/app/*`,
      '*': `${this.APP_BASE}node_modules/*`,
      ['lodash']: `${this.APP_BASE}node_modules/lodash/index`,
      'angular2-modal/plugins/bootstrap': `${this.APP_BASE}node_modules/angular2-modal/bundles/angular2-modal.bootstrap.umd.js`
    } );

    this.mergeObject( this.SYSTEM_BUILDER_CONFIG.paths, {
      ['lodash'] : `node_modules/lodash/index.js`,
      ['angular2-modal/plugins/bootstrap']: `node_modules/angular2-modal/plugins/bootstrap/index.js`
    });

```

**Comment by Marcelh29** [comment]
@iherbivore  bundling works when I change `import 'angular2-jwt'` in `'angular2-jwt/angular2-jwt'` but I have more external libraries that I added to my SYSTEM_BUILDER_CONFIG like ng2-translate, moment and primeng. I should change all my imports to the actual path to get bundling working for all these librarues. I guess there could be fix/instruction to be able to keep importing just 'angular2-jwt', 'ng2-translate' etc.

**Comment by hhubik** [comment]
Undid the Seed update from last night.  Everything works again.

**Comment by eppsilon** [comment]
There was a change yesterday (reverted today) that may have caused your issues. Could you try with the latest version of the seed? (See https://github.com/mgechev/angular-seed/pull/1495.)

**Comment by Marcelh29** [comment]
@eppsilon thanks for the reply. Its fixed in the latest version.

**Comment by hhubik** [comment]
@eppsilon - I just got the latest Seed.  Unfortunately, the problem with the file-saver library came right back.  Perhaps I am using the library incorrectly, but I would still like to understand why the latest Seed causes my code to fail (could it be the upgrade to Typescript 2.0.3?).

**Comment by eppsilon** [comment]
@hhubik I think you need something in SYSTEM_CONFIG_DEV that maps `file-saver` to `node_modules/file-saver/FileSaver.js`. Does the `file-saver` package have a `main` property in its `package.json` that points at `FileSaver.js`? If it does, I wonder if [this change](https://github.com/mgechev/angular-seed/commit/b972f1221c7340980d3da9eae548a33a71e2ea08) may be the reason it broke for you.

**Comment by hhubik** [comment]
@eppsilon - Thanks for the message. Here is the [file-saver package.json](https://github.com/eligrey/FileSaver.js/blob/master/package.json).  The `main` property indeed points to `FileSaver.js`.  Therefore I have put this in my `project.config.ts`:
```
      this.SYSTEM_CONFIG_DEV.paths['file-saver'] =
      `${this.APP_BASE}node_modules/file-saver/FileSaver`;

    this.SYSTEM_BUILDER_CONFIG.packages['file-saver'] = {
        main: 'FileSaver.js',
        defaultExtension : 'js'
    };
```

However, even with that, my app still fails to load with this error message:
`http://localhost:5555/node_modules/file-saver.js 404 (Not Found)`
How do I make the URL to be `http://localhost:5555/node_modules/file-saver/FileSaver.js`?

**Comment by hhubik** [comment]
@eppsilon - the above change to `SYSTEM_CONFIG_DEV` and `SYSTEM_BUILDER_CONFIG` in the end did the trick.  I had to manually re-compile my ts files in /tools and re-start the server. Thanks for the advice.
